version: "3"

services:
  yt_postgres:
    image: postgres:12
    container_name: yt_postgres
    volumes:
      - yt_postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
    command: -p $POSTGRES_PORT

  CRUDAPI:
    expose:
      - 8000
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    image: yt_docker:latest
    container_name: yt_docker
    depends_on:
      - yt_postgres
    volumes:
      - cache-python:/root/.cache/pip #$HOME/.cache/pip
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - ./AuthService/.env
      - .env
    environment:
      POSTGRES_HOST: "yt_postgres"
      DOCKER_START: 1
    command: >
      bash -c "./CRUDAPI/manage.py collectstatic --noinput && ./CRUDAPI/manage.py migrate && ./CRUDAPI/manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx
    container_name: yt_nginx
    depends_on:
      - CRUDAPI
    ports:
      - "8000:80"
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  static_volume:
  media_volume:
  yt_postgres-volume:
  cache-python:

