
upstream auth_backend {
    server CRUDAPI:8000;
}

upstream composite_backend {
    server composite-data-restapi:8000;
}

server {
    listen 80;

    location ~* /static/ {
        root /yt/backend/static;
    }

    location /api/vAUTH/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_set_header Host $http_host; # issue a socket
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://auth_backend;
    }
    location /api/vICOD/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_set_header Host $http_host; # issue a socket
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://composite_backend;
    }
}
