
upstream backend {
    server CRUDAPI:8000;
}

server {
    listen 80;

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_pass http://backend;
    }
}
