#FROM nginx:latest

#RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx.conf /etc/nginx/conf.d
#COPY proxy_params /etc/nginx


#FROM jwilder/nginx-proxy:1.2

#COPY default_location /etc/nginx/vhost.d/default_location
