"""empty message

Revision ID: 03e1d136a18b
Revises: 7b64f5b5a08a
Create Date: 2026-04-21 01:37:03.964033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e1d136a18b'
down_revision: Union[str, Sequence[str], None] = '7b64f5b5a08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'composite', ['id'])
    op.create_unique_constraint(None, 'composite', ['name'])
    op.create_unique_constraint(None, 'date_time', ['id'])
    op.create_unique_constraint(None, 'file_composite', ['id'])
    op.create_unique_constraint(None, 'fire_value', ['id'])
    op.create_unique_constraint(None, 'satellite', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'satellite', type_='unique')
    op.drop_constraint(None, 'fire_value', type_='unique')
    op.drop_constraint(None, 'file_composite', type_='unique')
    op.drop_constraint(None, 'date_time', type_='unique')
    op.drop_constraint(None, 'composite', type_='unique')
    op.drop_constraint(None, 'composite', type_='unique')
    # ### end Alembic commands ###
