"""Init

Revision ID: 7b64f5b5a08a
Revises: 
Create Date: 2026-04-20 20:28:09.147250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b64f5b5a08a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('date_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datetime'),
    sa.UniqueConstraint('id')
    )
    op.create_table('satellite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('file_composite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('access_tiles', sa.Boolean(), nullable=False),
    sa.Column('datetime_id', sa.Integer(), nullable=False),
    sa.Column('composite_id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composite_id'], ['composite.id'], ),
    sa.ForeignKeyConstraint(['datetime_id'], ['date_time.id'], ),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('fire_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('resolution', sa.SmallInteger(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('datetime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datetime_id'], ['date_time.id'], ),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fire_value')
    op.drop_table('file_composite')
    op.drop_table('satellite')
    op.drop_table('date_time')
    op.drop_table('composite')
    # ### end Alembic commands ###
