"""change field access_tiles

Revision ID: f1713813d910
Revises: d1b75ec910f9
Create Date: 2026-05-24 22:52:44.589467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1713813d910'
down_revision: Union[str, Sequence[str], None] = 'd1b75ec910f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('file_composite') as bop:
        bop.alter_column('access_tiles', new_column_name='is_downloadable_tiles')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('file_composite') as bop:
        bop.alter_column('is_downloadable_tiles', new_column_name='access_tiles')

    # ### end Alembic commands ###
