upstream server-auth-app {
    server server-auth:8000;
}

upstream server-account-app {
    server server-account:8000;
}

upstream server-docs-agregator-app {
    server server-docs-agregator:8000;
}

upstream server-info-composite-app {
    server server-info-composite:8000;
}

upstream server-composite-data-app {
    server server-composite-data:8000;
}

server {
    listen ${SERVER_PORT} ssl;
    server_name ${SERVER_NAME};

    ssl_certificate     ${SSL_CERTIFICATE_PATH};
    ssl_certificate_key ${SSL_CERTIFICATE_KEY_PATH};
    ssl_session_timeout 10m;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
    ssl_session_tickets off;
    ssl_session_cache shared:le_nginx_SSL:10m;

    set $route_to_files '/usr/src/app/AccountProject';

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location ~* /tiles/.+\.(png)$ {
        root /usr/src/;
    }

    location ~* /static/.+\.(js|css|woff|svg|png)$ {
        expires 365d;
        root $route_to_files;
    }

    proxy_set_header Origin $http_origin;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Ssl $https;


    location /docs/swagger/ {
        proxy_redirect off;
        proxy_pass http://server-docs-agregator-app;
    }

    location /api/vauth/ {
        proxy_redirect off;
        proxy_pass http://server-auth-app;
    }

    location /api/vaccount/ {
        proxy_redirect off;
        proxy_pass http://server-account-app;
    }

    location /api/vicod/ {
        proxy_redirect off;
        proxy_pass http://server-info-composite-app;
    }

    location /api/vcd/ {
        proxy_redirect off;
        proxy_pass http://server-composite-data-app;
    }
}