# Generated by Django 4.2.26 on 2025-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
