# Generated by Django 4.2.26 on 2025-11-29 09:40

import AccountApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_usermodel_is_verify'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', AccountApp.models.UserManagerCustom()),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_verify',
        ),
    ]
