# Generated by Django 4.2.26 on 2026-04-08 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0003_alter_usermodel_managers_remove_usermodel_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
