# Generated by Django 4.2.26 on 2026-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0004_optusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='optusermodel',
            name='next_code_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
