# Generated by Django 4.2.26 on 2026-04-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0005_optusermodel_next_code_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='optusermodel',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='optusermodel',
            name='notification_type_opt',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Verify register'), (2, 'Verify register email'), (3, 'Verify reset password')], default=0),
        ),
    ]
