# Generated by Django 4.2.26 on 2026-04-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0006_optusermodel_confirm_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptUserModel',
            new_name='OTPUserModel',
        ),
        migrations.RenameField(
            model_name='otpusermodel',
            old_name='notification_type_opt',
            new_name='notification_type_otp',
        ),
        migrations.RenameField(
            model_name='otpusermodel',
            old_name='opt_code',
            new_name='otp_code',
        ),
    ]
