# Generated by Django 4.2.26 on 2026-04-15 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0007_rename_optusermodel_otpusermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
