# Generated by Django 4.2.26 on 2026-04-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0008_otpusermodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='otpusermodel',
            table='otp_user',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
