# Generated by Django 4.2.26 on 2026-04-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0009_alter_usermodel_options_alter_otpusermodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='auth_user',
        ),
    ]
