# Generated by Django 4.2.26 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0010_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='organization_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='organization_name'),
        ),
    ]
