"""initial migrations

Revision ID: 40a0a21b7d14
Revises: 
Create Date: 2026-06-16 23:46:33.492978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '40a0a21b7d14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_polygon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polygon', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('file_composite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('is_downloadable_tiles', sa.Boolean(), nullable=False),
    sa.Column('composite_polygon_id', sa.Integer(), nullable=False),
    sa.Column('datetime_id', sa.Integer(), nullable=False),
    sa.Column('composite_id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['composite_polygon_id'], ['composite_polygon.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_file_composite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_composite_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('polygon', Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('datetime_expiration', sa.DateTime(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_composite_id'], ['file_composite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('download_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('file_composite_id', sa.Integer(), nullable=True),
    sa.Column('user_file_composite_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime_expiration', sa.DateTime(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_composite_id'], ['file_composite.id'], ),
    sa.ForeignKeyConstraint(['user_file_composite_id'], ['user_file_composite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('download_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('download_link_id', sa.Integer(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['download_link_id'], ['download_link.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download_history')
    op.drop_table('download_link')
    op.drop_table('user_file_composite')
    op.drop_table('file_composite')
    op.drop_table('composite_polygon')
    # ### end Alembic commands ###
