# Generated by Django 4.2.26 on 2026-06-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='AccountApp_usermodel',
        ),
    ]
